DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS ACCOUNTS;

CREATE TABLE `CUSTOMER` (
    `CUSTOMER_ID` INT AUTO_INCREMENT PRIMARY KEY,
    `NAME` VARCHAR(100) NOT NULL,
    `EMAIL` VARCHAR(100) NOT NULL,
    `MOBILE_NUMBER` VARCHAR(20) NOT NULL,
    `CREATE_DT` DATE DEFAULT NULL
);

CREATE TABLE `ACCOUNTS` (
                            `CUSTOMER_ID` INT NOT NULL,
                            `ACCOUNT_NUMBER` INT AUTO_INCREMENT PRIMARY KEY,
                            `ACCOUNT_TYPE` VARCHAR(100) NOT NULL,
                            `BRANCH_ADDRESS` VARCHAR(200) NOT NULL,
                            `CREATE_DT` DATE DEFAULT NULL
);
INSERT INTO `ACCOUNTS` (`CUSTOMER_ID`, `ACCOUNT_NUMBER`, `ACCOUNT_TYPE`, `BRANCH_ADDRESS`, `CREATE_DT`)
VALUES(1, 111222333, 'SAVINGS', '123 MAIN ST, NY', CURDATE());
INSERT INTO `CUSTOMER` (`NAME`, `EMAIL`, `MOBILE_NUMBER`, `CREATE_DT`)
VALUES('ALICE', 'ALICE@MSI.COM', '1234567890', CURDATE());
