version: "3.8"

services:
  configserver:
    image: polo1jcw/configserver
    mem_limit: 1024m
    ports:
      - "8071:8071"
    networks:
      - msi-network
  eurekaserver:
    image: polo1jcw/eurekaserver
    mem_limit: 1000m
    ports:
      - "8069:8069"
    networks:
      - msi-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

  accounts:
    image: polo1jcw/accounts
    mem_limit: 900m
    ports:
      - "8080:8080"
    networks:
      - msi-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_APPLICATION_NAME: accounts
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8069/eureka/
  loans:
    image: polo1jcw/loans
    mem_limit: 1024m
    ports:
      - "8090:8090"
    networks:
      - msi-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_APPLICATION_NAME: loans
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8069/eureka/
  cards:
    image: polo1jcw/cards
    mem_limit: 900m
    ports:
      - "8060:8060"
    networks:
      - msi-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_APPLICATION_NAME: CARDS
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8069/eureka/
networks:
  msi-network: